<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Solonoid" Id="{032de96a-05c3-4377-b62b-03f1d955d720}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'call_after_init'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FINAL FB_Solonoid EXTENDS FB_AbstractDevice IMPLEMENTS I_Device

VAR
	_output : REFERENCE TO BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_Init" Id="{e8927a36-8d54-4bc2-aa68-2691156b8a82}">
      <Declaration><![CDATA[//FB_Init is always available implicitly and it is used primarily for initialization.
//The return value is not evaluated. For a specific influence, you can also declare the
//methods explicitly and provide additional code there with the standard initialization
//code. You can evaluate the return value.
METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; // TRUE: the retain variables are initialized (reset warm / reset cold)
    bInCopyCode: BOOL;  // TRUE: the instance will be copied to the copy code afterward (online change)   
	output : REFERENCE TO BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[_output REF= output;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>